const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const Income = require('./income');
const params = { monthlySalary: 8000, workDaysPerMonth: 20, workStartTime: '09:00', workEndTime: '18:00', breakStartTime: '12:00', breakEndTime: '13:00', status: '专注搬砖', studyStatus: '认真学习' };
const at = (h, m = 0) => Income.computeState(params, new Date(2026, 8, 14, h, m));
assert.equal(Income.timeToMinutes('24:30'), null);
assert.equal(Income.minutesToTime(Income.timeToMinutes('24:00')), '24:00');
assert.throws(() => Income.validateTimes({ workEndTime: '24:01' }));
assert.equal(at(8).status, '未开工');
assert.equal(at(10).status, '专注搬砖');
assert.equal(at(10).studyStatus, '认真学习');
assert.equal(at(12, 30).status, '休息中');
assert.equal(at(12).income, at(13).income);
assert.equal(Income.computeState(at(12, 30), new Date(2026, 8, 14, 13)).status, '专注搬砖');
assert.equal(at(18).status, '今日完成');
assert.equal(at(18).income, 400);
assert.equal(at(22).progress, 100);
const nodes = new Map();
const node = id => { if (!nodes.has(id)) nodes.set(id, { textContent: '', style: {}, addEventListener() {} }); return nodes.get(id); };
const renderErrors = [];
const context = vm.createContext({ Income, console: { ...console, error: (...args) => renderErrors.push(args) }, document: { getElementById: node, addEventListener() {} }, window: { electronAPI: { onRefreshData() {}, onConfigChanged() {} } }, setInterval() {} });
const source = fs.readFileSync(require.resolve('./renderer.js'), 'utf8').split('// 启动')[0];
vm.runInContext(source, context);
vm.runInContext('fetchData()', context);
assert.equal(renderErrors.length, 0, 'Refresh before configuration is ready should be ignored');
vm.runInContext(`config = { mock: ${JSON.stringify(params)} }; render({ income: 123.45, progress: 42, status: '接口状态' }); tickCompute();`, context);
assert.equal(node('income').textContent, '123.45');
assert.equal(node('percent').textContent, '42.0%');
assert.equal(node('status').textContent, '接口状态');
console.log('PASS 时间边界、自动状态、收入封顶、外部 API 显示');
